apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-netcoreweb-web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-netcoreweb-web
    spec:
      containers:
        - name: demo-netcoreweb-web
          image: acrdemo01.azurecr.io/demo-netcoreweb-web:19
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-netcoreweb-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demo-netcoreweb-web